#!  /usr/bin/env python
# 
# Copyright (C) 2009  The University of Texas at Austin.
# 
# This file is part of Hydra: A wireless multihop testbed.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 

{"ip" : "192.168.255.1", "mac" : "0A:48:D5:09:F5:A9"}
# {"ip" : "192.168.255.2", "mac" : "FF:0A:C1:E8:DB:02"}
# {"ip" : "192.168.255.3", "mac" : "FA:2A:EC:D4:A7:FC"}
{"mtu": 2236, 'tun-device': "/dev/net/tun", "dev-name": "hydra-tun"}

